#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : R-psych
Version  : 2.5.3
Release  : 79
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/psych_2.5.3.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/psych_2.5.3.tar.gz
Summary  : Procedures for Psychological, Psychometric, and Personality
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-GPArotation
Requires: R-mnormt
BuildRequires : R-GPArotation
BuildRequires : R-mnormt
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%prep
%setup -q -n psych
pushd ..
cp -a psych buildavx2
popd
pushd ..
cp -a psych buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1742763660

%install
export SOURCE_DATE_EPOCH=1742763660
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/psych/CITATION
/usr/lib64/R/library/psych/DESCRIPTION
/usr/lib64/R/library/psych/INDEX
/usr/lib64/R/library/psych/Meta/Rd.rds
/usr/lib64/R/library/psych/Meta/data.rds
/usr/lib64/R/library/psych/Meta/features.rds
/usr/lib64/R/library/psych/Meta/hsearch.rds
/usr/lib64/R/library/psych/Meta/links.rds
/usr/lib64/R/library/psych/Meta/nsInfo.rds
/usr/lib64/R/library/psych/Meta/package.rds
/usr/lib64/R/library/psych/Meta/vignette.rds
/usr/lib64/R/library/psych/NAMESPACE
/usr/lib64/R/library/psych/NEWS.Rd
/usr/lib64/R/library/psych/R/psych
/usr/lib64/R/library/psych/R/psych.rdb
/usr/lib64/R/library/psych/R/psych.rdx
/usr/lib64/R/library/psych/data/Rdata.rdb
/usr/lib64/R/library/psych/data/Rdata.rds
/usr/lib64/R/library/psych/data/Rdata.rdx
/usr/lib64/R/library/psych/doc/index.html
/usr/lib64/R/library/psych/doc/scoring.R
/usr/lib64/R/library/psych/doc/scoring.Rnw
/usr/lib64/R/library/psych/doc/scoring.pdf
/usr/lib64/R/library/psych/help/AnIndex
/usr/lib64/R/library/psych/help/aliases.rds
/usr/lib64/R/library/psych/help/paths.rds
/usr/lib64/R/library/psych/help/psych.rdb
/usr/lib64/R/library/psych/help/psych.rdx
/usr/lib64/R/library/psych/html/00Index.html
/usr/lib64/R/library/psych/html/R.css
/usr/lib64/R/library/psych/tests/testthat/ReadMe.text
/usr/lib64/R/library/psych/tests/testthat/test_ICC.R
/usr/lib64/R/library/psych/tests/testthat/test_corPlot.r
/usr/lib64/R/library/psych/tests/testthat/test_fa.r
/usr/lib64/R/library/psych/tests/testthat/test_lmCor.r
/usr/lib64/R/library/psych/tests/testthat/test_lowercor.r
/usr/lib64/R/library/psych/tests/testthat/test_mediate.r
/usr/lib64/R/library/psych/tests/testthat/test_omega.r
/usr/lib64/R/library/psych/tests/testthat/test_splitHalf.r
/usr/lib64/R/library/psych/tests/testthat/test_tetrachoric..r
